name: Run Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest:20.04

    steps:
      - uses: actions/shell@v2
        with:
          args: bash make.sh
          
