name: Run bash script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest:20.04

    steps:
      - uses: actions/shell@v2

      - name: Run Script
        run: bash make.sh
        
